### ISSUE TITLE
Can you edit values?

### ISSUE THREAD

**Issue by TatriX** [randomPoison/amethyst-editor#32]
Nice project! Can you edit values like translation and rotation?

**Comment by randomPoison** [comment]
Not yet, but that's the next thing I want to work on! I'm currently working on getting a 0.2 release out to fix some (rather egregious) bugs in the 0.1 release, but after that I'm going to try to get some super basic runtime editing support going. I'll try to get a tracking issue open for that soon so that it'll be a bit easier to see what the progress is 🙂

**Comment by TatriX** [comment]
Can I somehow help you?

**Comment by randomPoison** [comment]
Unfortunately there's not much room to share the work for setting up edit support, since I need to get the core chunk implemented first. But if you're interested in contributing to the editor in general then there are a number of things you could work on 🙂

The ["good first issue"](https://github.com/randomPoison/amethyst-editor/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) tag is a good place to start. Right now, there's #11 in this repo, as well as randomPoison/amethyst-editor-sync#22 and randomPoison/amethyst-editor-sync#1. If you want to help out with any of those, feel free to leave a comment on the ticket you want to work on. I'm also happy to answer any questions and offer mentorship if that'd be helpful :grin:

**Comment by randomPoison** [comment]
Okay, I've got PR #34 up that adds the basic functionality for runtime editing, I should be able to get it merged soon. I've created a project for tracking work on runtime editing and have added some tickets to track the next work that needs to be done: https://github.com/randomPoison/amethyst-editor/projects/6. They all should open for you (or anyone else) to work on if you'd still like to contribute 🙂

Now that I have issue tracking in place for the remaining editing functionality, I'm going to go ahead and close this issue.
